function datafilepointer = staircaseSetup(subNo, prepair)
%------------------------------------------
% SCRIPT HEADER
%------------------------------------------
try
	tableVariable = {'subNo', ...     % variable names to print to outfile
				   'index', ...
				   'mean', ...
				   'periodicity', ...
				   'nEvents', ...  								 
				   'pressedKey', ...
				   'answer', ...
				   'isCorrect', ...
				   'rt', ...
				   'reversal', ...
				   's1',...
				   's2',...
				   's3',...
				   's4',...
				   's5',...
				   's6',...
				   's7',...
				   's8',...
				   's9',...
				   's10',...
				   's11',...
				   's12',...
				   's13',...
				   's14',...
				   's15',...
				   's16',...
				   's17',...
				   's18',...
				   's19',...
				   's20',...
				   't1',...
				   't2',...
				   't3',...
				   't4',...
				   't5',...
				   't6',...
				   't7',...
				   't8',...
				   't9',...
				   't10',...
				   't11',...
				   't12',...
				   't13',...
				   't14',...
				   't15',...
				   't16',...
				   't17',...
				   't18',...
				   't19',...
				   'seqDuration', ...
				   'startInterval', ...
				   'trialDuration'};

    filename = strcat('P_' ,num2str(subNo), '_staircase');

	datafilepointer = ml_open_files(subNo, prepair.outFolder, ...    % open output files:
	 								prepair.nOutfile, filename, ...
	  								prepair.isLogfile); 
	
	ml_writetofile(datafilepointer(1), tableVariable);    % print headings to outfiles

	GetSecs; 											  % initiate timing functions
	WaitSecs(1);
    %---------------------
catch ME
    rethrow(ME);
end
%------------------------------------------