function staircaseSaveData(subNo, fpointer, Sequence, ResponseData, reversal)
%FUNCTION_HEADER - 
% 
% Syntax:  [y] = FUNCTION_HEADER(x)
%
% Input: 
%           x:             
%
% Output:
% 
%           y:            
%
% Example:
%
%           [y] = FUNCTION_HEADER(x)
%
% m-files required: none
% Subfunctions: none
% MAT-files required: none
%
% Author: David C Greatrex
% Work Address: Centre for Music and Science, Cambridge University
% email: dcg32@cam.ac.uk
% Website: http://www.davidgreatrex.com
% mmm YYYY; Last revision: DD-MM-YYYY
 
%------------------------------------------
data = {subNo, ...
        Sequence.index, ...
        Sequence.mu, ...
        Sequence.isPeriodic, ...
        ResponseData.nEvents, ...
        ResponseData.pressedKey, ...
		ResponseData.answer, ...
		ResponseData.isCorrect, ...
		ResponseData.RT, ...
		reversal, ...
		Sequence.targetArray(1), ...
		Sequence.targetArray(2), ...
		Sequence.targetArray(3), ...
		Sequence.targetArray(4), ...
		Sequence.targetArray(5), ...
		Sequence.targetArray(6), ...
		Sequence.targetArray(7), ...
		Sequence.targetArray(8), ...
		Sequence.targetArray(9), ...
		Sequence.targetArray(10), ...
		Sequence.targetArray(11), ...
		Sequence.targetArray(12), ...
		Sequence.targetArray(13), ...
		Sequence.targetArray(14), ...
		Sequence.targetArray(15), ...
		Sequence.targetArray(16), ...
		Sequence.targetArray(17), ...
		Sequence.targetArray(18), ...
		Sequence.targetArray(19), ...
		Sequence.targetArray(20), ...
		Sequence.IOIarray(1), ...
		Sequence.IOIarray(2), ...
		Sequence.IOIarray(3), ...
		Sequence.IOIarray(4), ...
		Sequence.IOIarray(5), ...
		Sequence.IOIarray(6), ...
		Sequence.IOIarray(7), ...
		Sequence.IOIarray(8), ...
		Sequence.IOIarray(9), ...
		Sequence.IOIarray(10), ...
		Sequence.IOIarray(11), ...
		Sequence.IOIarray(12), ...
		Sequence.IOIarray(13), ...
		Sequence.IOIarray(14), ...
		Sequence.IOIarray(15), ...
		Sequence.IOIarray(16), ...
		Sequence.IOIarray(17), ...
		Sequence.IOIarray(18), ...
		Sequence.IOIarray(19), ...
		Sequence.duration, ...
		ResponseData.startInterval, ...
		ResponseData.totalDuration};

ml_writetofile(fpointer, data); % print data to outfiles
%------------------------------------------